  
DROP DATABASE UPLOAD;
create DATABASE UPLOAD;
USE UPLOAD;

CREATE TABLE USER(
    ID int NOT NULL AUTO_INCREMENT,
    EMAIL varchar(255) NOT NULL,
    PASSWORD varchar(255) NOT NULL,
    ROLE varchar(255) NOT NULL,
    EMAILCODE varchar(255),
    PRIMARY KEY (ID),
    UNIQUE KEY unique_email (EMAIL)
);

CREATE TABLE PHOTO(
    ID int NOT NULL AUTO_INCREMENT,
    USER_ID int NOT NULL,
    FILENAME varchar(255),
    TITLE varchar(255),
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE,
    CONSTRAINT USER_FILENAME UNIQUE (USER_ID,FILENAME)
);