### see all photos shared with me
GET http://localhost:80/Client/SharedWithMe
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1leHZhbmNlMDRAZ21haWwuY29tIiwiYXV0aG9yaXphdGlvbiI6ImNsaWVudCIsImlhdCI6MTU4ODgyMjA2NCwiZXhwIjoxNTg4ODIzODY0fQ.Mh71OdbD_mMwVgmZNO-OxuyEeTAGDvyeHtQm4Xq39CE

