### Getting the full res version of a photo
GET http://localhost:80/Photos/FullRes/photo1.jpg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGVyLmRheWJlbGw5NkBnbWFpbC5jb20iLCJhdXRob3JpemF0aW9uIjoicGhvdG9ncmFwaGVyIiwiaWF0IjoxNTg4MjcwNzU4LCJleHAiOjE1ODgyNzI1NTh9.xjwQk-H77J2d6YJRgRkp0_wS-BCn_XoYhjz3tFKiT08