### Adding a client to the viewers table so that they can access a photo
POST http://localhost:80/Photographer/GrantClientPermissions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGVyLmRheWJlbGw5NkBnbWFpbC5jb20iLCJhdXRob3JpemF0aW9uIjoiY2xpZW50IiwiaWF0IjoxNTg4ODE3OTExLCJleHAiOjE1ODg4MTk3MTF9.Iau9LrPh0bPMhgm1pFULgVqnuxiId3eyBcjATv4prsg
Content-Type: application/json

{	
	"Email":"mexvance04@gmail.com",
    "Photo":"81f45400-9009-11ea-b24d-e7a058bc4d00.jpg",
    "Permission":"Full_Res"
}

### getting photos by user email note: you must be logged in as this user
GET http://localhost:80/Photographer/MyPhotos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGVyLmRheWJlbGw5NkBnbWFpbC5jb20iLCJhdXRob3JpemF0aW9uIjoiY2xpZW50IiwiaWF0IjoxNTg4ODE3OTExLCJleHAiOjE1ODg4MTk3MTF9.Iau9LrPh0bPMhgm1pFULgVqnuxiId3eyBcjATv4prsg

