### Getting the full res version of a photo
GET http://localhost:80/Photos/FullRes/39a14cd0-8bc2-11ea-998a-6b5b205711bf.jpg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGVyLmRheWJlbGw5NkBnbWFpbC5jb20iLCJhdXRob3JpemF0aW9uIjoicGhvdG9ncmFwaGVyIiwiaWF0IjoxNTg4MzQ2ODEyLCJleHAiOjE1ODgzNDg2MTJ9.XuYePs87Zk_zrCQsK7-rKtK6c6jqr2pA_dt1_SnC3vM
### getting the low res version of an image
GET http://localhost:80/Photos/LowRes/photo1.jpg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGVyLmRheWJlbGw5NkBnbWFpbC5jb20iLCJhdXRob3JpemF0aW9uIjoicGhvdG9ncmFwaGVyIiwiaWF0IjoxNTg4MjczNzU1LCJleHAiOjE1ODgyNzU1NTV9.IujZQVN2Ss3t_UGi-AUgL37hxE6iAa08UWr3whN4c1s

### getting photos by user email note: you must be logged in as this user
GET http://localhost:80/Photos/MyPhotos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGVyLmRheWJlbGw5NkBnbWFpbC5jb20iLCJhdXRob3JpemF0aW9uIjoicGhvdG9ncmFwaGVyIiwiaWF0IjoxNTg4MzQ2ODEyLCJleHAiOjE1ODgzNDg2MTJ9.XuYePs87Zk_zrCQsK7-rKtK6c6jqr2pA_dt1_SnC3vM