### Adding a client to the viewers table so that they can access a photo
POST http://localhost:80/Photographer/GrantClientPermissions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGVyLmRheWJlbGw5NkBnbWFpbC5jb20iLCJhdXRob3JpemF0aW9uIjoicGhvdG9ncmFwaGVyIiwiaWF0IjoxNTg4ODk1NTc3LCJleHAiOjE1ODg4OTczNzd9.ZLqcZzPnhpXAiLpUmFTyUQB5eyzSfZi-bdzZ_HQbnjA
Content-Type: application/json

{	
	"Email":"relyk.photography.kyler@gmail.com",
    "Photo":"be5d84c0-90bd-11ea-a286-7b716fddf4cc.jpg",
    "Permission":"Full_Res"
}

### getting photos by user email note: you must be logged in as this user
GET http://localhost:80/Photographer/MyPhotos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGVyLmRheWJlbGw5NkBnbWFpbC5jb20iLCJhdXRob3JpemF0aW9uIjoicGhvdG9ncmFwaGVyIiwiaWF0IjoxNTg4OTAwNDQ4LCJleHAiOjE1ODg5MDIyNDh9.C52faMfL90RHKns00CKyxr7DKWDYrdqQDdDizxJW8TU


